class AudioSamples {

    constructor()  {
        this.preparse()
    }

    preparse() {
        let url = 'https://' + window.location.host + '/storage/records/';
    
        for (let index in this.list) {
          let sample = this.list[index];
          sample.audio = url + index + '.mp3';
        }
    }

    list = [
        { text: `Perhaps you'd better look after the kid`},
      
        { text: `We have been running this fishing school for three years and haven't had a dissatisfied customer yet`},
        { text: `Now we've all got to know each other's names, we'll have some coffee`},
        { text: `Two enormous green eyes had appeared among the leaves`},
        { text: `...and then he ate some radishes...`},
        { text: `Next to his house was a piece of broken board...`},
        { text: `The silence in the dark house was broken only by the distant, grunting snores...`},
        { text: `...so you had brought the green one...`},
        { text: `...like a leaf caught in an eddy`},
        { text: `...and the whole story had come out`},
        { text: `...that has to be done in the morning...`},
        
        { text: `He drank some wine slowly`},
        { text: `The two men drank`},
        { text: `...it was driven by Mr. McGregor`},
        { text: `I drove from Minneapolis to Florida by back roads...`},
        { text: `...but he didn't feel like eating alone.`},
        { text: `He had never felt so lonely`},
        { text: `Simon felt clean, and relaxed, and hungry`},   
        { text: `You have forgotten the magic word`},    
        { text: `Christopher Robin gave a deep sigh...`},    
        { text: `...gone forever...`},    
        
        { text: `I grew a beard`},    
        { text: `He has gone to see his friend Pooh Bear...`},    
        { text: `I heard you quite well the first time`},    
        { text: `I wish you would bring it out here`},    
        { text: `...the real ending became inevitable`},    
        { text: `...because of an almost invisible scar`},    
        { text: `...Harry kept waking in the night...`},    
        { text: `...and I kept travelling...`},    
        { text: `...and l kept writing...`},    
        { text: `...so he kept himself in shape...`},       
      
        { text: `...until he had learnt it off by heart`},     
        { text: `Harry left through the back door`},    
        { text: `You must have left it somewhere`},    
        { text: `...in case he lost one...`},    
        { text: `...you made a mistake`},    
        { text: `...it made us rich`},    
        { text: `Booked doesn't necessarily mean paid for, Mr Shaw`},    
        { text: `They let me down`},    
        { text: `Ernest picked up the phone`},    
        { text: `What are you doing tonight?`},    
        
        { text: `Jason isn't looking rehabilitated`},    
        { text: `Lizetty works as a customer service rep for 24000 dollars a year`},    
        { text: `We live in this basement apartment`},    
        { text: `And he owns the house with another guy`},    
        { text: `This is hard`},    
        { text: `Jason is so frustrated`},    
        { text: `Dealing with bad drivers is like trying to hurt cats`},    
        { text: `And you are the only one who can help me`},    
        { text: `I am currently between homes`},    
        { text: `I can find anyone or anything if the price is right`}, 
    
        { text: `I don't like being lectured`},    
        { text: `...the executive committee meeting has already been put off twice...`},    
        { text: `Have you got your gun?`},    
        { text: `...when the doorbell rang...`},    
        { text: `So for a week Christopher Robin read that sort of book...`},    
        { text: `...and then he saw a friend of his`},    
        { text: `...you saw how it was...`},    
        { text: `...that he had seen something like it somewhere...`},    
        { text: `Eyeore shook his had from side to side`},    
        { text: `...and the house might be sold by next week`},    
        
        { text: `He stood up and stared out of the window at the square...`},    
        { text: `...when l was stuck...`},    
        { text: `He took off his jacket`},    
        { text: `He took out a plump leg of lamb`},    
        { text: `He opened the fridge and took out a bottle of champagne`},    
        { text: `Somebody must have taken it`},    
        { text: `He gazed miserably into the hedge`},    
        { text: `Why are you staring at the hedge?`},    
        { text: `He did as he was told`},    
        { text: `...and he told the truth...`},    
        
        { text: `He took the champagne from the fridge`},    
        { text: `It was unblemished and unmarked`},    
        { text: `...and his shirt felt uncomfortably tight against his stomach`},    
        { text: `Belinda went up the stairs into the undecorated part of the house`},    
        { text: `...was thick with two years of undisturbed dust`},    
        { text: `uhelpful comment`},    
        { text: `...and then, suddenly and unprofessionally she hugged him`},    
        { text: `We will be shopping for a holiday home in Majorca this time tomorrow`},    
        { text: `You won't be too sorry to go, will you?`},    
        { text: `You will brake the habit of a lifetime, won't you?`},    
        
        { text: `What would you like to eat?`},    
        { text: `I'd never written anything divisive before`},    
        { text: `l wrote a letter to my agent`},    
        { text: `So right now you have the the best partner in the world and you're screwing it up really`},    
        { text: `...l work very, very hard. l like to reward myself`},    
        { text: `...lt's just a metaphor, dude`},    
        { text: `l need this cigarettes`},    
        { text: `...you can have your whatever you gonna have, I'll have this`},    
        { text: `...you keep anticipating what Lizetty wants and you keep freakin' guessing wrong, dude!`},    
        { text: `...Lizetty worries that Ryan's eating out`},    
        
        { text: `What can l do for you boys?`},    
        { text: `...Deep debt and overdue taxes are hurting their marriage`},    
        { text: `...How much is the coffee?`},    
        { text: `Now with the baby on the way there is even more at stake!`},    
        { text: `Maybe I'll have to raise this kid by myself...`},    
        { text: `...How much is tea? Fifty- three cents...`},    
        { text: `...l just talked to him because he was the only guy...`},    
        { text: `...And l thought he was reading Shakespeare...`},    
        { text: `...so he began to climb the tree...`},    
        { text: `Peter began to cry...`},    
        
        { text: `...She bought her loaf of brown bread...`},    
        { text: `...He came to a pond...`},    
        { text: `...He came to an open place in the middle of the forest...`},    
        { text: `...Mr Mc Gregor cought sight of him at the corner.`},    
        { text: `...l can eat it...`},    
        { text: `...Then flew gracefully into a gorse bush`},    
        { text: `...He found the door  in the wall...`},    
        { text: `...And then he got up...`},    
        { text: `He was enjoying his job. Although he wanted something that would challenge him more than it did`},    
        { text: `lt'll roll all over again`},    
        
        { text: `She sells seashells by the sea shore`},    
        { text: `...But his eyes got larger and larger and his face got pinker and pinker...`},    
        { text: `...He lost one of his shoes among the cabbages`},    
        { text: `That book was made by Mr Mark Twain`},    
        { text: `The same trend can be seen in Britain`},    
        { text: `On the morning of May eighteenth...`},    
        { text: `...He's now been going for a.. forty six minutes`},    
        { text: `Ryan earns a commission based income of ninety thousand dollars a year...`},    
        { text: `His mother put him to bed...`},    
        { text: `...He ran on four legs...`},    
        
        { text: `Average hourly earnings rose by 4.7 percent in April the biggest monthly gain on record`},    
        { text: `"I'll try", l said`},    
        { text: `...He sang a little song to himself...`},    
        { text: `...Peter sat down to rest`},    
        { text: `...She sat very, very still...`},    
        { text: `She was a very beautiful young woman, although she look tired and fragile now...`},    
        { text: `...He could smell the honey`},    
        { text: `Then you had better have the blue balloon...`},    
        { text: `He went back to his work`},    
        { text: `You look young. Clean living`},    

        { text: `Are you exited? Nervous? Both.`},
        { text: `Can l get you anything?`},    
        { text: `Can we talk? Please?`},    
        { text: `Didn't we have a deal?`},    
        { text: `Does everyone here knows?`},    
        { text: `Hello, Fred. How are you?`},    
        { text: `How about you?`},    
        { text: `How are you holding up, really?`},    
        { text: `Dont rush this time Betty`},    
        { text: `My day just got a lot more interesting`},    

        { text: `And I'm proud of you...`},
        { text: `Because l love you exactly the way you are`},    
        { text: `Can l just say something?`},    
        { text: `Dont beat yourself up.14`},    
        { text: `Dont fall for it`},    
        { text: `Dont worry I'm a grown man`},    
        { text: `Everything was fine...`},    
        { text: `Hang on...`},    
        { text: `He's kind of a Mama's boy. Kind of?`},    
        { text: `Hey, are you okay? - Not really. - What's going on?`},    
        
        { text: `Hey, boys! How's it going?`},
        { text: `How long do you think he'll stay?`},    
        { text: `How's it working out?`},    
        { text: `I - l just was reaching out for the help you know`},    
        { text: `I - lm not sure. Maybe a few days`},    
        { text: `I did do that..mp3`},    
        { text: `I just want to get out of the house and spend some money`},    
        { text: `I take it back. l belive it`},    
        { text: `I want to thank you all so much for coming`},    
        { text: `I was off work for six months...`},    

        { text: `Lets see. Youre better than us...`},
        { text: `If you meant what you just said...`},    
        { text: `I'll make you a deal`},    
        { text: `I'm sorry, I shouldn't have said that`},    
        { text: `I'm sure, it's extremely frustrating`},    
        { text: `It's more than that`},    
        { text: `It's OK. I'm fine`},    
        { text: `It's true`},    
        { text: `Maybe feel little bit down...`},    
        { text: `My name's Bill. My wife... er... Tasia. We have two children, Lucas and Olivia. I have my own business`},    

        { text: `No, it doesn't`},
        { text: `Oh, that makes sense 'cause she's gone and you miss her`},    
        { text: `OK, uh, let's get things started`},    
        { text: `Say your name`},    
        { text: `Sheldon, dinner's ready`},    
        { text: `So you're gonna throw me under the bus?`},    
        { text: `Sometimes people say things they don't mean`},    
        { text: `That's a solution for everything`},    
        { text: `That's what I'm here for`},    
        { text: `Then why didn't you say that?`},    

        { text: `Try another one`},
        { text: `Using our credit cards a lot more`},    
        { text: `We are in financial truble`},    
        { text: `We know we have this debt looming over our heads`},    
        { text: `We owe you an apology`},    
        { text: `We're still in the process of building the business`},    
        { text: `What difference does it make?`},    
        { text: `What do you think I'm feeling right now?`},    
        { text: `What does it say I'm feeling?`},    
        { text: `What have l done with my life?`},
        
        { text: `What is wrong with you?`},    
        { text: `Why would you do that Raj?`},    
        { text: `Wouldn't that be nice?`},    
        { text: `Yeah sounds great. See you then`},    
        { text: `Wow l find that hard to belive`},    
        { text: `You are - happy?`},    
        { text: `You don't have a problem with this, do you?`},    
        { text: `You know the same thing happened to me`},    
        { text: `You need to go back to work`},    
        { text: `How was the ride`},    
        
        { text: `I don't want to hear it, Mom. lt's happening. I'm going`},    
        { text: `I get that`},    
        { text: `I'll catch you guys soon`},    
        { text: `I'll get the bags. Would you?`},    
        { text: `I'll set it up`},    
        { text: `I'm not doing this. That's up to you`},    
        { text: `Is everything okay?`},    
        { text: `Is he your boyfriend?`},    
        { text: `Is it all it is? Just friends?`},    
        { text: `Is that your thing?`},    

        { text: `Make an appointment`},    
        { text: `No disrespect Dad`},    
        { text: `Or is that not okay? No, no. lt's okay`},    
        { text: `So how's your first day going? Good?`},    
        { text: `That's it. We don't talk anymore?`},    
        { text: `There we go. Looking good`},    
        { text: `Wait, that was you signing, something you wrote?`},    
        { text: `What are we doing?`},    
        { text: `What can I do for you, Mr. Andrews?`},    
        { text: `What did you say to me?`},    

        { text: `What happened?`},    
        { text: `What were you saying?`},    
        { text: `What, you've got something better to do?`},    
        { text: `What's up coach?`},    
        { text: `Who are you lying to?`},    
        { text: `Why are you being so nice?`},    
        { text: `Why are you being so nice?`},    
        { text: `Why is that?`},    
        { text: `You are a sight for sore eyes`},    
        { text: `Wonderful`},    

        { text: `Most of the girls in the village have broken their hearts over him at one time or another`},    
        { text: `Perhaps you'd better look after the kid`},       
    ]
}

export default (new AudioSamples).list